import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL,
  process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY
)

async function extractInternalLinks(html, baseUrl) {
  const origin = new URL(baseUrl).origin
  const linkRegex = /<a[^>]+href=["']([^"']+)["'][^>]*>/gi
  const links = new Set()
  links.add(baseUrl)
  let match
  while ((match = linkRegex.exec(html)) !== null) {
    let href = match[1]
    if (href.startsWith('/') && !href.startsWith('//')) {
      href = origin + href
    } else if (!href.startsWith('http')) {
      continue
    }
    // Only internal links, skip anchors/assets
    if (href.startsWith(origin) && 
        !href.includes('#') &&
        !href.match(/\.(pdf|jpg|jpeg|png|gif|svg|css|js|ico|xml|txt)$/i)) {
      links.add(href)
    }
  }
  return [...links].slice(0, 5)
}

async function extractJsFiles(html, baseUrl) {
  const scriptRegex = /<script[^>]+src=["']([^"']+)["'][^>]*>/gi
  const matches = []
  let match
  while ((match = scriptRegex.exec(html)) !== null) {
    let src = match[1]
    if (src.startsWith('//')) src = 'https:' + src
    else if (src.startsWith('/')) src = new URL(baseUrl).origin + src
    else if (!src.startsWith('http')) src = new URL(src, baseUrl).href
    if (!src.includes(new URL(baseUrl).hostname) &&
        (src.includes('cdn') || src.includes('googleapis') ||
         src.includes('analytics') || src.includes('gtag'))) continue
    matches.push(src)
  }
  return matches.slice(0, 10)
}

async function extractInlineScripts(html) {
  const inlineRegex = /<script(?![^>]*src)[^>]*>([\s\S]*?)<\/script>/gi
  const scripts = []
  let match
  while ((match = inlineRegex.exec(html)) !== null) {
    const content = match[1].trim()
    if (content.length > 100) {
      scripts.push(content.slice(0, 3000))
    }
  }
  return scripts
}

async function extractCssFiles(html, baseUrl) {
  const cssRegex = /<link[^>]+href=["']([^"']+\.css[^"']*)["'][^>]*>/gi
  const matches = []
  let match
  while ((match = cssRegex.exec(html)) !== null) {
    let href = match[1]
    if (href.startsWith('/')) href = new URL(baseUrl).origin + href
    else if (!href.startsWith('http')) href = new URL(href, baseUrl).href
    if (href.includes(new URL(baseUrl).hostname)) {
      matches.push(href)
    }
  }
  return matches.slice(0, 3)
}

async function fetchContent(url) {
  const res = await fetch(url, {
    headers: { 'User-Agent': 'Mozilla/5.0' },
    signal: AbortSignal.timeout(5000)
  })
  return await res.text()
}

async function analyzePage(url) {
  const pageRes = await fetch(url, {
    headers: { 'User-Agent': 'Mozilla/5.0' },
    signal: AbortSignal.timeout(10000)
  })
  const html = await pageRes.text()

  // External JS
  const jsUrls = await extractJsFiles(html, url)
  const jsFiles = []
  for (const jsUrl of jsUrls) {
    try {
      const text = await fetchContent(jsUrl)
      const lineCount = (text.match(/\n/g) || []).length
      const isMinified = text.length > 1000 && lineCount < 10
      jsFiles.push({ url: jsUrl, code: text.slice(0, 8000), minified: isMinified })
    } catch (e) {}
  }

  // Inline scripts
  const inlineScripts = await extractInlineScripts(html)

  // CSS files
  const cssUrls = await extractCssFiles(html, url)
  const cssFiles = []
  for (const cssUrl of cssUrls) {
    try {
      const text = await fetchContent(cssUrl)
      cssFiles.push({ url: cssUrl, code: text.slice(0, 3000) })
    } catch (e) {}
  }

  // Build payload
  let codePayload = `=== HTML (first 3000 chars) ===\n${html.slice(0, 3000)}\n\n`

  if (inlineScripts.length > 0) {
    inlineScripts.forEach((s, i) => {
      codePayload += `=== INLINE SCRIPT ${i + 1} ===\n${s}\n\n`
    })
  }

  if (jsFiles.length > 0) {
    jsFiles.forEach((f, i) => {
      codePayload += `=== JS FILE ${i + 1}: ${f.url} ${f.minified ? '(minified)' : ''} ===\n${f.code}\n\n`
    })
  }

  if (cssFiles.length > 0) {
    cssFiles.forEach((f, i) => {
      codePayload += `=== CSS FILE ${i + 1}: ${f.url} ===\n${f.code}\n\n`
    })
  }

  const claudeRes = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': process.env.ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01'
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 1024,
      messages: [{
        role: 'user',
        content: `You are an expert at detecting whether code was written by a human or generated by AI tools like GitHub Copilot, ChatGPT, v0.dev, or Cursor.

Analyze the following web code and return ONLY valid JSON with no markdown:
{
  "ai_probability": <0-100 integer, where 100 = definitely AI>,
  "verdict": <"likely_human" | "mixed" | "likely_ai" | "almost_certainly_ai">,
  "confidence": <"low" | "medium" | "high">,
  "reasoning": "<3-4 sentence explanation of key signals>",
  "signals": {
    "ai_indicators": ["list of specific AI-like patterns found"],
    "human_indicators": ["list of specific human-like patterns found"]
  }
}

Key signals to look for:
AI indicators: perfectly uniform indentation, generic variable names (data, result, item), boilerplate comments, cookie-cutter component structure, excessive abstraction for simple tasks, v0/Copilot/ChatGPT artifacts, overly consistent naming conventions, no typos or fixup commits visible in code comments
Human indicators: inconsistent style, creative/unconventional naming, TODO comments, personal shortcuts, unusual patterns, custom logic, domain-specific vocabulary, debugging artifacts, commented-out experiments

Code to analyze:
${codePayload}`
      }]
    })
  })

  const claudeData = await claudeRes.json()
  const text = claudeData.content[0].text
  const result = JSON.parse(text.replace(/```json|```/g, '').trim())

  return {
    url,
    score: result.ai_probability,
    verdict: result.verdict,
    confidence: result.confidence,
    reasoning: result.reasoning,
    signals: result.signals,
    filesAnalyzed: jsFiles.length + inlineScripts.length + cssFiles.length
  }
}

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  const { url, userId } = req.body
  if (!url) return res.status(400).json({ error: 'URL is required' })

  // Check scan limit
  if (userId) {
    let { data: userData } = await supabase
      .from('users')
      .select('*')
      .eq('user_id', userId)
      .single()

    if (!userData) {
      const { data: newUser } = await supabase
        .from('users')
        .insert({ user_id: userId, scan_limit: 3, scans_used: 0 })
        .select()
        .single()
      userData = newUser
    }

    if (userData && userData.scans_used >= userData.scan_limit) {
      return res.status(403).json({
        error: 'Monthly limit reached',
        limitReached: true
      })
    }
  }

  try {
    // Fetch homepage and extract internal links
    const homepageRes = await fetch(url, {
      headers: { 'User-Agent': 'Mozilla/5.0' },
      signal: AbortSignal.timeout(10000)
    })
    const homepageHtml = await homepageRes.text()
    const pages = await extractInternalLinks(homepageHtml, url)

    // Analyze each page sequentially
    const pageResults = []
    for (const pageUrl of pages) {
      try {
        const result = await analyzePage(pageUrl)
        pageResults.push(result)
      } catch (e) {
        pageResults.push({ url: pageUrl, error: e.message })
      }
    }

    // Calculate overall score
    const validResults = pageResults.filter(r => !r.error)
    const overallScore = validResults.length > 0
      ? Math.round(validResults.reduce((sum, r) => sum + r.score, 0) / validResults.length)
      : 0

    const getVerdict = (score) => {
      if (score < 30) return 'likely_human'
      if (score < 55) return 'mixed'
      if (score < 75) return 'likely_ai'
      return 'almost_certainly_ai'
    }

    // Save to scans table
    await supabase.from('scans').insert({
      url,
      score: overallScore,
      verdict: getVerdict(overallScore),
      report: { pages: pageResults, overallScore },
      status: 'complete',
      user_id: userId || null
    })

    // Increment scans_used
    if (userId) {
      const { data: currentUser } = await supabase
        .from('users')
        .select('scans_used')
        .eq('user_id', userId)
        .single()

      await supabase
        .from('users')
        .update({ scans_used: (currentUser?.scans_used || 0) + 1 })
        .eq('user_id', userId)
    }

    return res.status(200).json({
      url,
      overallScore,
      verdict: getVerdict(overallScore),
      pagesScanned: pageResults.length,
      pages: pageResults
    })

  } catch (err) {
    console.error(err)
    return res.status(500).json({ error: 'Crawl failed', details: err.message })
  }
}