import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL,
  process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY
)

async function extractJsFiles(html, baseUrl) {
  const scriptRegex = /<script[^>]+src=["']([^"']+)["'][^>]*>/gi
  const matches = []
  let match
  while ((match = scriptRegex.exec(html)) !== null) {
    let src = match[1]
    if (src.startsWith('//')) src = 'https:' + src
    else if (src.startsWith('/')) src = new URL(baseUrl).origin + src
    else if (!src.startsWith('http')) src = new URL(src, baseUrl).href
    // skip CDN/third-party scripts
    if (!src.includes(new URL(baseUrl).hostname) && 
        (src.includes('cdn') || src.includes('googleapis') || 
         src.includes('analytics') || src.includes('gtag'))) continue
    matches.push(src)
  }
  return matches.slice(0, 5) // max 5 JS files
}

async function fetchJsContent(urls) {
  const contents = []
  for (const url of urls) {
    try {
      const res = await fetch(url, { 
        headers: { 'User-Agent': 'Mozilla/5.0' },
        signal: AbortSignal.timeout(5000)
      })
      const text = await res.text()
      // skip minified files that are too long with no newlines
      const lineCount = (text.match(/\n/g) || []).length
      const isMinified = text.length > 1000 && lineCount < 10
      if (!isMinified) {
        contents.push({ url, code: text.slice(0, 2000) })
      } else {
        // for minified, take a smaller sample
        contents.push({ url, code: text.slice(0, 500), minified: true })
      }
    } catch (e) {
      // skip files that fail to load
    }
  }
  return contents
}

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  const { url, userId } = req.body
  if (!url) return res.status(400).json({ error: 'URL is required' })

  // Check scan limit
  if (userId) {
    const now = new Date()
    const firstOfMonth = new Date(now.getFullYear(), now.getMonth(), 1).toISOString()
    
    const { count } = await supabase
      .from('scans')
      .select('*', { count: 'exact', head: true })
      .eq('user_id', userId)
      .gte('created_at', firstOfMonth)

    if (count >= 3) {
      return res.status(403).json({ 
        error: 'Monthly limit reached',
        limitReached: true
      })
    }
  }

  try {
    const pageRes = await fetch(url, { 
      headers: { 'User-Agent': 'Mozilla/5.0' },
      signal: AbortSignal.timeout(10000)
    })
    const html = await pageRes.text()

    // Extract JS file URLs
    const jsUrls = await extractJsFiles(html, url)

    // Fetch JS file contents
    const jsFiles = await fetchJsContent(jsUrls)

    // Build analysis payload
    let codePayload = `=== HTML HEAD (first 1000 chars) ===\n${html.slice(0, 1000)}\n\n`

    if (jsFiles.length > 0) {
      jsFiles.forEach((f, i) => {
        codePayload += `=== JS FILE ${i + 1}: ${f.url} ${f.minified ? '(minified)' : ''} ===\n${f.code}\n\n`
      })
    } else {
      codePayload += `=== PAGE SOURCE (no external JS found) ===\n${html.slice(0, 3000)}`
    }

    const claudeRes = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 1024,
        messages: [{
          role: 'user',
          content: `You are an expert at detecting whether code was written by a human or generated by AI tools like GitHub Copilot, ChatGPT, or v0.dev.

Analyze the following web code and return ONLY valid JSON with no markdown:
{
  "ai_probability": <0-100 integer, where 100 = definitely AI>,
  "verdict": <"likely_human" | "mixed" | "likely_ai" | "almost_certainly_ai">,
  "reasoning": "<2-3 sentence explanation of key signals>",
  "signals": {
    "ai_indicators": ["list of specific AI-like patterns found"],
    "human_indicators": ["list of specific human-like patterns found"]
  }
}

Key signals to look for:
AI indicators: perfectly uniform indentation, generic variable names (data, result, item), boilerplate comments, cookie-cutter component structure, excessive abstraction for simple tasks, v0/Copilot/ChatGPT artifacts
Human indicators: inconsistent style, creative/unconventional naming, TODO comments, personal shortcuts, unusual patterns, custom logic, domain-specific vocabulary

Code to analyze:
${codePayload}`
        }]
      })
    })

    const claudeData = await claudeRes.json()
    const text = claudeData.content[0].text
    const result = JSON.parse(text.replace(/```json|```/g, '').trim())

    await supabase.from('scans').insert({
      url,
      score: result.ai_probability,
      verdict: result.verdict,
      report: result,
      status: 'complete',
      user_id: userId || null
    })

    return res.status(200).json({
      url,
      score: result.ai_probability,
      verdict: result.verdict,
      reasoning: result.reasoning,
      signals: result.signals,
      filesAnalyzed: jsFiles.length
    })

  } catch (err) {
    console.error(err)
    return res.status(500).json({ error: 'Scan failed', details: err.message })
  }
}