import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL,
  process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY
)

async function extractJsFiles(html, baseUrl) {
  const scriptRegex = /<script[^>]+src=["']([^"']+)["'][^>]*>/gi
  const matches = []
  let match
  while ((match = scriptRegex.exec(html)) !== null) {
    let src = match[1]
    if (src.startsWith('//')) src = 'https:' + src
    else if (src.startsWith('/')) src = new URL(baseUrl).origin + src
    else if (!src.startsWith('http')) src = new URL(src, baseUrl).href
    if (!src.includes(new URL(baseUrl).hostname) && 
        (src.includes('cdn') || src.includes('googleapis') || 
         src.includes('analytics') || src.includes('gtag'))) continue
    matches.push(src)
  }
  return matches.slice(0, 5)
}

async function fetchJsContent(urls) {
  const contents = []
  for (const url of urls) {
    try {
      const res = await fetch(url, { 
        headers: { 'User-Agent': 'Mozilla/5.0' },
        signal: AbortSignal.timeout(5000)
      })
      const text = await res.text()
      const lineCount = (text.match(/\n/g) || []).length
      const isMinified = text.length > 1000 && lineCount < 10
      if (!isMinified) {
        contents.push({ url, code: text.slice(0, 2000) })
      } else {
        contents.push({ url, code: text.slice(0, 500), minified: true })
      }
    } catch (e) {}
  }
  return contents
}

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  const { url, userId } = req.body
  if (!url) return res.status(400).json({ error: 'URL is required' })

  // Check scan limit from users table
  if (userId) {
    let { data: userData } = await supabase
      .from('users')
      .select('*')
      .eq('user_id', userId)
      .single()

    if (!userData) {
      const { data: newUser } = await supabase
        .from('users')
        .insert({ user_id: userId, scan_limit: 3, scans_used: 0 })
        .select()
        .single()
      userData = newUser
    }

    // Check if reset_date has passed and reset if so
    if (userData) {
      const today = new Date().toISOString().split('T')[0]
      if (userData.reset_date && today >= userData.reset_date) {
        const newResetDate = new Date()
        newResetDate.setMonth(newResetDate.getMonth() + 1)
        await supabase
          .from('users')
          .update({ 
            scans_used: 0, 
            reset_date: newResetDate.toISOString().split('T')[0] 
          })
          .eq('user_id', userId)
        userData.scans_used = 0
      }

      if (userData.scans_used >= userData.scan_limit) {
        return res.status(403).json({ 
          error: 'Monthly limit reached',
          limitReached: true
        })
      }
    }
  }

  try {
    const pageRes = await fetch(url, { 
      headers: { 'User-Agent': 'Mozilla/5.0' },
      signal: AbortSignal.timeout(10000)
    })
    const html = await pageRes.text()

    const jsUrls = await extractJsFiles(html, url)
    const jsFiles = await fetchJsContent(jsUrls)

    let codePayload = `=== HTML HEAD (first 1000 chars) ===\n${html.slice(0, 1000)}\n\n`
    if (jsFiles.length > 0) {
      jsFiles.forEach((f, i) => {
        codePayload += `=== JS FILE ${i + 1}: ${f.url} ${f.minified ? '(minified)' : ''} ===\n${f.code}\n\n`
      })
    } else {
      codePayload += `=== PAGE SOURCE (no external JS found) ===\n${html.slice(0, 3000)}`
    }

    const claudeRes = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 1024,
        messages: [{
          role: 'user',
          content: `You are an expert at detecting whether code was written by a human or generated by AI tools like GitHub Copilot, ChatGPT, or v0.dev.

Analyze the following web code and return ONLY valid JSON with no markdown:
{
  "ai_probability": <0-100 integer, where 100 = definitely AI>,
  "verdict": <"likely_human" | "mixed" | "likely_ai" | "almost_certainly_ai">,
  "reasoning": "<2-3 sentence explanation of key signals>",
  "signals": {
    "ai_indicators": ["list of specific AI-like patterns found"],
    "human_indicators": ["list of specific human-like patterns found"]
  }
}

Key signals to look for:
AI indicators: perfectly uniform indentation, generic variable names (data, result, item), boilerplate comments, cookie-cutter component structure, excessive abstraction for simple tasks, v0/Copilot/ChatGPT artifacts
Human indicators: inconsistent style, creative/unconventional naming, TODO comments, personal shortcuts, unusual patterns, custom logic, domain-specific vocabulary

Code to analyze:
${codePayload}`
        }]
      })
    })

    const claudeData = await claudeRes.json()
    const text = claudeData.content[0].text
    const result = JSON.parse(text.replace(/```json|```/g, '').trim())

    // Save scan to scans table
    await supabase.from('scans').insert({
      url,
      score: result.ai_probability,
      verdict: result.verdict,
      report: result,
      status: 'complete',
      user_id: userId || null
    })

    // Increment scans_used in users table
    if (userId) {
      await supabase
        .from('users')
        .update({ scans_used: supabase.rpc('increment', { row_id: userId }) })
        .eq('user_id', userId)

      // Simpler approach - just increment directly
      const { data: currentUser } = await supabase
        .from('users')
        .select('scans_used')
        .eq('user_id', userId)
        .single()

      await supabase
        .from('users')
        .update({ scans_used: (currentUser?.scans_used || 0) + 1 })
        .eq('user_id', userId)
    }

    return res.status(200).json({
      url,
      score: result.ai_probability,
      verdict: result.verdict,
      reasoning: result.reasoning,
      signals: result.signals,
      filesAnalyzed: jsFiles.length
    })

  } catch (err) {
    console.error(err)
    return res.status(500).json({ error: 'Scan failed', details: err.message })
  }
}